[build]
  publish = "./"

[[headers]]
  for = "/map.html"
  [headers.values]
    Basic-Auth = "admin:pass1234"
    X-Robots-Tag = "noindex, nofollow, noarchive"
    Cache-Control = "no-store"

[[headers]]
  for = "/data/*"
  [headers.values]
    Basic-Auth = "admin:pass1234"
    X-Robots-Tag = "noindex, nofollow, noarchive"
    Cache-Control = "no-store"
